version: "3.5"
services:
  nginx:
    container_name: nginx
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.docker/nginx/logs/:/var/log/nginx/
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/sites-available/:/etc/nginx/sites-available/
      - ./etc/nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - ./etc/nginx/ssl-conf/:/etc/nginx/ssl-conf/
      - ./etc/letsencrypt/:/etc/letsencrypt/
      - ./www/:/var/www/
    env_file: .env
    restart: unless-stopped
    command: /bin/sh -c "while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;'"

  certbot:
    container_name: certbot
    build:
      context: ./.docker/certbot
      dockerfile: Dockerfile
    volumes:
      - ./.docker/certbot/logs/:/var/log/letsencrypt/
      - ./etc/letsencrypt/:/etc/letsencrypt/
      - ./www/certbot/:/var/www/certbot/
    depends_on:
      - nginx
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"

networks:
  default:
    name: docker-server-network
    driver: bridge
